<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('physical_currency', function (Blueprint $table) {
            $table->id();
            $table->string('currency_code', 20);
            $table->string('currency_name');
            $table->string('url_image')->nullable();
            $table->string('country_code', 20)->nullable();
            $table->timestamps();
        });

        DB::table('physical_currency')->insert(
            [
                [
                    'currency_code' => 'AED',
                    'currency_name' => 'United Arab Emirates Dirham',
                    'url_image' => 'https://flagsapi.com/AE/flat/64.png',
                    'country_code' => 'AE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AFN',
                    'currency_name' => 'Afghan Afghani',
                    'url_image' => 'https://flagsapi.com/AF/flat/64.png',
                    'country_code' => 'AF',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ALL',
                    'currency_name' => 'Albanian Lek',
                    'url_image' => 'https://flagsapi.com/AL/flat/64.png',
                    'country_code' => 'AL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AMD',
                    'currency_name' => 'Armenian Dram',
                    'url_image' => 'https://flagsapi.com/AM/flat/64.png',
                    'country_code' => 'AM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ANG',
                    'currency_name' => 'Netherlands Antillean Guilder',
                    'url_image' => 'https://flagsapi.com/AN/flat/64.png',
                    'country_code' => 'AN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AOA',
                    'currency_name' => 'Angolan Kwanza',
                    'url_image' => 'https://flagsapi.com/AO/flat/64.png',
                    'country_code' => 'AO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ARS',
                    'currency_name' => 'Argentine Peso',
                    'url_image' => 'https://flagsapi.com/AR/flat/64.png',
                    'country_code' => 'AR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AUD',
                    'currency_name' => 'Australian Dollar',
                    'url_image' => 'https://flagsapi.com/AU/flat/64.png',
                    'country_code' => 'AU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AWG',
                    'currency_name' => 'Aruban Florin',
                    'url_image' => 'https://flagsapi.com/AW/flat/64.png',
                    'country_code' => 'AW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'AZN',
                    'currency_name' => 'Azerbaijani Manat',
                    'url_image' => 'https://flagsapi.com/AZ/flat/64.png',
                    'country_code' => 'AZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BAM',
                    'currency_name' => 'Bosnia-Herzegovina Convertible Mark',
                    'url_image' => 'https://flagsapi.com/BA/flat/64.png',
                    'country_code' => 'BA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BBD',
                    'currency_name' => 'Barbadian Dollar',
                    'url_image' => 'https://flagsapi.com/BB/flat/64.png',
                    'country_code' => 'BB',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BDT',
                    'currency_name' => 'Bangladeshi Taka',
                    'url_image' => 'https://flagsapi.com/BD/flat/64.png',
                    'country_code' => 'BD',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BGN',
                    'currency_name' => 'Bulgarian Lev',
                    'url_image' => 'https://flagsapi.com/BG/flat/64.png',
                    'country_code' => 'BG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BHD',
                    'currency_name' => 'Bahraini Dinar',
                    'url_image' => 'https://flagsapi.com/BH/flat/64.png',
                    'country_code' => 'BH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BIF',
                    'currency_name' => 'Burundian Franc',
                    'url_image' => 'https://flagsapi.com/BI/flat/64.png',
                    'country_code' => 'BI',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BMD',
                    'currency_name' => 'Bermudan Dollar',
                    'url_image' => 'https://flagsapi.com/BM/flat/64.png',
                    'country_code' => 'BM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BND',
                    'currency_name' => 'Brunei Dollar',
                    'url_image' => 'https://flagsapi.com/BN/flat/64.png',
                    'country_code' => 'BN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BOB',
                    'currency_name' => 'Bolivian Boliviano',
                    'url_image' => 'https://flagsapi.com/BO/flat/64.png',
                    'country_code' => 'BO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BRL',
                    'currency_name' => 'Brazilian Real',
                    'url_image' => 'https://flagsapi.com/BR/flat/64.png',
                    'country_code' => 'BR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BSD',
                    'currency_name' => 'Bahamian Dollar',
                    'url_image' => 'https://flagsapi.com/BS/flat/64.png',
                    'country_code' => 'BS',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BTN',
                    'currency_name' => 'Bhutanese Ngultrum',
                    'url_image' => 'https://flagsapi.com/BT/flat/64.png',
                    'country_code' => 'BT',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BWP',
                    'currency_name' => 'Botswanan Pula',
                    'url_image' => 'https://flagsapi.com/BW/flat/64.png',
                    'country_code' => 'BW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'BZD',
                    'currency_name' => 'Belize Dollar',
                    'url_image' => 'https://flagsapi.com/BZ/flat/64.png',
                    'country_code' => 'BZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CAD',
                    'currency_name' => 'Canadian Dollar',
                    'url_image' => 'https://flagsapi.com/CA/flat/64.png',
                    'country_code' => 'CA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CDF',
                    'currency_name' => 'Congolese Franc',
                    'url_image' => 'https://flagsapi.com/CD/flat/64.png',
                    'country_code' => 'CD',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CHF',
                    'currency_name' => 'Swiss Franc',
                    'url_image' => 'https://flagsapi.com/CH/flat/64.png',
                    'country_code' => 'CH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CLF',
                    'currency_name' => 'Chilean Unit of Account UF',
                    'url_image' => 'https://flagsapi.com/CL/flat/64.png',
                    'country_code' => 'CL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CLP',
                    'currency_name' => 'Chilean Peso',
                    'url_image' => 'https://flagsapi.com/CL/flat/64.png',
                    'country_code' => 'CL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CNH',
                    'currency_name' => 'Chinese Yuan Offshore',
                    'url_image' => 'https://flagsapi.com/CN/flat/64.png',
                    'country_code' => 'CN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CNY',
                    'currency_name' => 'Chinese Yuan',
                    'url_image' => 'https://flagsapi.com/CN/flat/64.png',
                    'country_code' => 'CN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'COP',
                    'currency_name' => 'Colombian Peso',
                    'url_image' => 'https://flagsapi.com/CO/flat/64.png',
                    'country_code' => 'CO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CUP',
                    'currency_name' => 'Cuban Peso',
                    'url_image' => 'https://flagsapi.com/CU/flat/64.png',
                    'country_code' => 'CU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CVE',
                    'currency_name' => 'Cape Verdean Escudo',
                    'url_image' => 'https://flagsapi.com/CV/flat/64.png',
                    'country_code' => 'CV',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'CZK',
                    'currency_name' => 'Czech Republic Koruna',
                    'url_image' => 'https://flagsapi.com/CZ/flat/64.png',
                    'country_code' => 'CZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'DJF',
                    'currency_name' => 'Djiboutian Franc',
                    'url_image' => 'https://flagsapi.com/DJ/flat/64.png',
                    'country_code' => 'DJ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'DKK',
                    'currency_name' => 'Danish Krone',
                    'url_image' => 'https://flagsapi.com/DK/flat/64.png',
                    'country_code' => 'DK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'DOP',
                    'currency_name' => 'Dominican Peso',
                    'url_image' => 'https://flagsapi.com/DO/flat/64.png',
                    'country_code' => 'DO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'DZD',
                    'currency_name' => 'Algerian Dinar',
                    'url_image' => 'https://flagsapi.com/DZ/flat/64.png',
                    'country_code' => 'DZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'EGP',
                    'currency_name' => 'Egyptian Pound',
                    'url_image' => 'https://flagsapi.com/EG/flat/64.png',
                    'country_code' => 'EG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ERN',
                    'currency_name' => 'Eritrean Nakfa',
                    'url_image' => 'https://flagsapi.com/ER/flat/64.png',
                    'country_code' => 'ER',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ETB',
                    'currency_name' => 'Ethiopian Birr',
                    'url_image' => 'https://flagsapi.com/ET/flat/64.png',
                    'country_code' => 'ET',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'EUR',
                    'currency_name' => 'Euro',
                    'url_image' => 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg',
                    'country_code' => 'EU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'FJD',
                    'currency_name' => 'Fijian Dollar',
                    'url_image' => 'https://flagsapi.com/FJ/flat/64.png',
                    'country_code' => 'FJ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'FKP',
                    'currency_name' => 'Falkland Islands Pound',
                    'url_image' => 'https://flagsapi.com/FK/flat/64.png',
                    'country_code' => 'FK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GBP',
                    'currency_name' => 'British Pound Sterling',
                    'url_image' => 'https://flagsapi.com/GB/flat/64.png',
                    'country_code' => 'GB',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GEL',
                    'currency_name' => 'Georgian Lari',
                    'url_image' => 'https://flagsapi.com/GE/flat/64.png',
                    'country_code' => 'GE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GHS',
                    'currency_name' => 'Ghanaian Cedi',
                    'url_image' => 'https://flagsapi.com/GH/flat/64.png',
                    'country_code' => 'GH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GIP',
                    'currency_name' => 'Gibraltar Pound',
                    'url_image' => 'https://flagsapi.com/GI/flat/64.png',
                    'country_code' => 'GI',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GMD',
                    'currency_name' => 'Gambian Dalasi',
                    'url_image' => 'https://flagsapi.com/GM/flat/64.png',
                    'country_code' => 'GM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GNF',
                    'currency_name' => 'Guinean Franc',
                    'url_image' => 'https://flagsapi.com/GN/flat/64.png',
                    'country_code' => 'GN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GTQ',
                    'currency_name' => 'Guatemalan Quetzal',
                    'url_image' => 'https://flagsapi.com/GT/flat/64.png',
                    'country_code' => 'GT',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'GYD',
                    'currency_name' => 'Guyanaese Dollar',
                    'url_image' => 'https://flagsapi.com/GY/flat/64.png',
                    'country_code' => 'GY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'HKD',
                    'currency_name' => 'Hong Kong Dollar',
                    'url_image' => 'https://flagsapi.com/HK/flat/64.png',
                    'country_code' => 'HK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'HNL',
                    'currency_name' => 'Honduran Lempira',
                    'url_image' => 'https://flagsapi.com/HN/flat/64.png',
                    'country_code' => 'HN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'HRK',
                    'currency_name' => 'Croatian Kuna',
                    'url_image' => 'https://flagsapi.com/HR/flat/64.png',
                    'country_code' => 'HR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'HTG',
                    'currency_name' => 'Haitian Gourde',
                    'url_image' => 'https://flagsapi.com/HT/flat/64.png',
                    'country_code' => 'HT',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'HUF',
                    'currency_name' => 'Hungarian Forint',
                    'url_image' => 'https://flagsapi.com/HU/flat/64.png',
                    'country_code' => 'HU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ICP',
                    'currency_name' => 'Internet Computer',
                    'url_image' => 'https://flagsapi.com/IC/flat/64.png',
                    'country_code' => 'IC',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'IDR',
                    'currency_name' => 'Indonesian Rupiah',
                    'url_image' => 'https://flagsapi.com/ID/flat/64.png',
                    'country_code' => 'ID',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ILS',
                    'currency_name' => 'Israeli New Sheqel',
                    'url_image' => 'https://flagsapi.com/IL/flat/64.png',
                    'country_code' => 'IL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'INR',
                    'currency_name' => 'Indian Rupee',
                    'url_image' => 'https://flagsapi.com/IN/flat/64.png',
                    'country_code' => 'IN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'IQD',
                    'currency_name' => 'Iraqi Dinar',
                    'url_image' => 'https://flagsapi.com/IQ/flat/64.png',
                    'country_code' => 'IQ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'IRR',
                    'currency_name' => 'Iranian Rial',
                    'url_image' => 'https://flagsapi.com/IR/flat/64.png',
                    'country_code' => 'IR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ISK',
                    'currency_name' => 'Icelandic Krona',
                    'url_image' => 'https://flagsapi.com/IS/flat/64.png',
                    'country_code' => 'IS',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'JEP',
                    'currency_name' => 'Jersey Pound',
                    'url_image' => 'https://flagsapi.com/JE/flat/64.png',
                    'country_code' => 'JE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'JMD',
                    'currency_name' => 'Jamaican Dollar',
                    'url_image' => 'https://flagsapi.com/JM/flat/64.png',
                    'country_code' => 'JM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'JOD',
                    'currency_name' => 'Jordanian Dinar',
                    'url_image' => 'https://flagsapi.com/JO/flat/64.png',
                    'country_code' => 'JO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'JPY',
                    'currency_name' => 'Japanese Yen',
                    'url_image' => 'https://flagsapi.com/JP/flat/64.png',
                    'country_code' => 'JP',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KES',
                    'currency_name' => 'Kenyan Shilling',
                    'url_image' => 'https://flagsapi.com/KE/flat/64.png',
                    'country_code' => 'KE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KGS',
                    'currency_name' => 'Kyrgystani Som',
                    'url_image' => 'https://flagsapi.com/KG/flat/64.png',
                    'country_code' => 'KG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KHR',
                    'currency_name' => 'Cambodian Riel',
                    'url_image' => 'https://flagsapi.com/KH/flat/64.png',
                    'country_code' => 'KH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KMF',
                    'currency_name' => 'Comorian Franc',
                    'url_image' => 'https://flagsapi.com/KM/flat/64.png',
                    'country_code' => 'KM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KPW',
                    'currency_name' => 'North Korean Won',
                    'url_image' => 'https://flagsapi.com/KP/flat/64.png',
                    'country_code' => 'KP',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KRW',
                    'currency_name' => 'South Korean Won',
                    'url_image' => 'https://flagsapi.com/KR/flat/64.png',
                    'country_code' => 'KR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KWD',
                    'currency_name' => 'Kuwaiti Dinar',
                    'url_image' => 'https://flagsapi.com/KW/flat/64.png',
                    'country_code' => 'KW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KYD',
                    'currency_name' => 'Cayman Islands Dollar',
                    'url_image' => 'https://flagsapi.com/KY/flat/64.png',
                    'country_code' => 'KY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'KZT',
                    'currency_name' => 'Kazakhstani Tenge',
                    'url_image' => 'https://flagsapi.com/KZ/flat/64.png',
                    'country_code' => 'KZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LAK',
                    'currency_name' => 'Laotian Kip',
                    'url_image' => 'https://flagsapi.com/LA/flat/64.png',
                    'country_code' => 'LA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LBP',
                    'currency_name' => 'Lebanese Pound',
                    'url_image' => 'https://flagsapi.com/LB/flat/64.png',
                    'country_code' => 'LB',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LKR',
                    'currency_name' => 'Sri Lankan Rupee',
                    'url_image' => 'https://flagsapi.com/LK/flat/64.png',
                    'country_code' => 'LK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LRD',
                    'currency_name' => 'Liberian Dollar',
                    'url_image' => 'https://flagsapi.com/LR/flat/64.png',
                    'country_code' => 'LR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LSL',
                    'currency_name' => 'Lesotho Loti',
                    'url_image' => 'https://flagsapi.com/LS/flat/64.png',
                    'country_code' => 'LS',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'LYD',
                    'currency_name' => 'Libyan Dinar',
                    'url_image' => 'https://flagsapi.com/LY/flat/64.png',
                    'country_code' => 'LY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MAD',
                    'currency_name' => 'Moroccan Dirham',
                    'url_image' => 'https://flagsapi.com/MA/flat/64.png',
                    'country_code' => 'MA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MDL',
                    'currency_name' => 'Moldovan Leu',
                    'url_image' => 'https://flagsapi.com/MD/flat/64.png',
                    'country_code' => 'MD',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MGA',
                    'currency_name' => 'Malagasy Ariary',
                    'url_image' => 'https://flagsapi.com/MG/flat/64.png',
                    'country_code' => 'MG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MKD',
                    'currency_name' => 'Macedonian Denar',
                    'url_image' => 'https://flagsapi.com/MK/flat/64.png',
                    'country_code' => 'MK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MMK',
                    'currency_name' => 'Myanma Kyat',
                    'url_image' => 'https://flagsapi.com/MM/flat/64.png',
                    'country_code' => 'MM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MNT',
                    'currency_name' => 'Mongolian Tugrik',
                    'url_image' => 'https://flagsapi.com/MN/flat/64.png',
                    'country_code' => 'MN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MOP',
                    'currency_name' => 'Macanese Pataca',
                    'url_image' => 'https://flagsapi.com/MO/flat/64.png',
                    'country_code' => 'MO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MRO',
                    'currency_name' => 'Mauritanian Ouguiya (pre-2018)',
                    'url_image' => 'https://flagsapi.com/MR/flat/64.png',
                    'country_code' => 'MR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MRU',
                    'currency_name' => 'Mauritanian Ouguiya',
                    'url_image' => 'https://flagsapi.com/MR/flat/64.png',
                    'country_code' => 'MR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MUR',
                    'currency_name' => 'Mauritian Rupee',
                    'url_image' => 'https://flagsapi.com/MU/flat/64.png',
                    'country_code' => 'MU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MVR',
                    'currency_name' => 'Maldivian Rufiyaa',
                    'url_image' => 'https://flagsapi.com/MV/flat/64.png',
                    'country_code' => 'MV',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MWK',
                    'currency_name' => 'Malawian Kwacha',
                    'url_image' => 'https://flagsapi.com/MW/flat/64.png',
                    'country_code' => 'MW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MXN',
                    'currency_name' => 'Mexican Peso',
                    'url_image' => 'https://flagsapi.com/MX/flat/64.png',
                    'country_code' => 'MX',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MYR',
                    'currency_name' => 'Malaysian Ringgit',
                    'url_image' => 'https://flagsapi.com/MY/flat/64.png',
                    'country_code' => 'MY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'MZN',
                    'currency_name' => 'Mozambican Metical',
                    'url_image' => 'https://flagsapi.com/MZ/flat/64.png',
                    'country_code' => 'MZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'NAD',
                    'currency_name' => 'Namibian Dollar',
                    'url_image' => 'https://flagsapi.com/NA/flat/64.png',
                    'country_code' => 'NA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'NGN',
                    'currency_name' => 'Nigerian Naira',
                    'url_image' => 'https://flagsapi.com/NG/flat/64.png',
                    'country_code' => 'NG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'NOK',
                    'currency_name' => 'Norwegian Krone',
                    'url_image' => 'https://flagsapi.com/NO/flat/64.png',
                    'country_code' => 'NO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'NPR',
                    'currency_name' => 'Nepalese Rupee',
                    'url_image' => 'https://flagsapi.com/NP/flat/64.png',
                    'country_code' => 'NP',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'NZD',
                    'currency_name' => 'New Zealand Dollar',
                    'url_image' => 'https://flagsapi.com/NZ/flat/64.png',
                    'country_code' => 'NZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'OMR',
                    'currency_name' => 'Omani Rial',
                    'url_image' => 'https://flagsapi.com/OM/flat/64.png',
                    'country_code' => 'OM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PAB',
                    'currency_name' => 'Panamanian Balboa',
                    'url_image' => 'https://flagsapi.com/PA/flat/64.png',
                    'country_code' => 'PA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PEN',
                    'currency_name' => 'Peruvian Nuevo Sol',
                    'url_image' => 'https://flagsapi.com/PE/flat/64.png',
                    'country_code' => 'PE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PGK',
                    'currency_name' => 'Papua New Guinean Kina',
                    'url_image' => 'https://flagsapi.com/PG/flat/64.png',
                    'country_code' => 'PG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PHP',
                    'currency_name' => 'Philippine Peso',
                    'url_image' => 'https://flagsapi.com/PH/flat/64.png',
                    'country_code' => 'PH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PKR',
                    'currency_name' => 'Pakistani Rupee',
                    'url_image' => 'https://flagsapi.com/PK/flat/64.png',
                    'country_code' => 'PK',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PLN',
                    'currency_name' => 'Polish Zloty',
                    'url_image' => 'https://flagsapi.com/PL/flat/64.png',
                    'country_code' => 'PL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'PYG',
                    'currency_name' => 'Paraguayan Guarani',
                    'url_image' => 'https://flagsapi.com/PY/flat/64.png',
                    'country_code' => 'PY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'QAR',
                    'currency_name' => 'Qatari Rial',
                    'url_image' => 'https://flagsapi.com/QA/flat/64.png',
                    'country_code' => 'QA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'RON',
                    'currency_name' => 'Romanian Leu',
                    'url_image' => 'https://flagsapi.com/RO/flat/64.png',
                    'country_code' => 'RO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'RSD',
                    'currency_name' => 'Serbian Dinar',
                    'url_image' => 'https://flagsapi.com/RS/flat/64.png',
                    'country_code' => 'RS',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'RUB',
                    'currency_name' => 'Russian Ruble',
                    'url_image' => 'https://flagsapi.com/RU/flat/64.png',
                    'country_code' => 'RU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'RUR',
                    'currency_name' => 'Old Russian Ruble',
                    'url_image' => 'https://flagsapi.com/RU/flat/64.png',
                    'country_code' => 'RU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'RWF',
                    'currency_name' => 'Rwandan Franc',
                    'url_image' => 'https://flagsapi.com/RW/flat/64.png',
                    'country_code' => 'RW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SAR',
                    'currency_name' => 'Saudi Riyal',
                    'url_image' => 'https://flagsapi.com/SA/flat/64.png',
                    'country_code' => 'SA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SBDf',
                    'currency_name' => 'Solomon Islands Dollar',
                    'url_image' => 'https://flagsapi.com/SB/flat/64.png',
                    'country_code' => 'SB',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SCR',
                    'currency_name' => 'Seychellois Rupee',
                    'url_image' => 'https://flagsapi.com/SC/flat/64.png',
                    'country_code' => 'SC',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SDG',
                    'currency_name' => 'Sudanese Pound',
                    'url_image' => 'https://flagsapi.com/SD/flat/64.png',
                    'country_code' => 'SD',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SDR',
                    'currency_name' => 'Special Drawing Rights',
                    'url_image' => 'https://flagsapi.com/SDR/flat/64.png',
                    'country_code' => 'SDR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SEK',
                    'currency_name' => 'Swedish Krona',
                    'url_image' => 'https://flagsapi.com/SE/flat/64.png',
                    'country_code' => 'SE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SGD',
                    'currency_name' => 'Singapore Dollar',
                    'url_image' => 'https://flagsapi.com/SG/flat/64.png',
                    'country_code' => 'SG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SHP',
                    'currency_name' => 'Saint Helena Pound',
                    'url_image' => 'https://flagsapi.com/SH/flat/64.png',
                    'country_code' => 'SH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SLL',
                    'currency_name' => 'Sierra Leonean Leone',
                    'url_image' => 'https://flagsapi.com/SL/flat/64.png',
                    'country_code' => 'SL',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SOS',
                    'currency_name' => 'Somali Shilling',
                    'url_image' => 'https://flagsapi.com/SO/flat/64.png',
                    'country_code' => 'SO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SRD',
                    'currency_name' => 'Surinamese Dollar',
                    'url_image' => 'https://flagsapi.com/SR/flat/64.png',
                    'country_code' => 'SR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SYP',
                    'currency_name' => 'Syrian Pound',
                    'url_image' => 'https://flagsapi.com/SY/flat/64.png',
                    'country_code' => 'SY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'SZL',
                    'currency_name' => 'Swazi Lilangeni',
                    'url_image' => 'https://flagsapi.com/SZ/flat/64.png',
                    'country_code' => 'SZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'THB',
                    'currency_name' => 'Thai Baht',
                    'url_image' => 'https://flagsapi.com/TH/flat/64.png',
                    'country_code' => 'TH',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TJS',
                    'currency_name' => 'Tajikistani Somoni',
                    'url_image' => 'https://flagsapi.com/TJ/flat/64.png',
                    'country_code' => 'TJ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TMT',
                    'currency_name' => 'Turkmenistani Manat',
                    'url_image' => 'https://flagsapi.com/TM/flat/64.png',
                    'country_code' => 'TM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TND',
                    'currency_name' => 'Tunisian Dinar',
                    'url_image' => 'https://flagsapi.com/TN/flat/64.png',
                    'country_code' => 'TN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TOP',
                    'currency_name' => 'Tongan Pa\'anga',
                    'url_image' => 'https://flagsapi.com/TO/flat/64.png',
                    'country_code' => 'TO',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TRY',
                    'currency_name' => 'Turkish Lira',
                    'url_image' => 'https://flagsapi.com/TR/flat/64.png',
                    'country_code' => 'TR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TTD',
                    'currency_name' => 'Trinidad and Tobago Dollar',
                    'url_image' => 'https://flagsapi.com/TT/flat/64.png',
                    'country_code' => 'TT',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TWD',
                    'currency_name' => 'New Taiwan Dollar',
                    'url_image' => 'https://flagsapi.com/TW/flat/64.png',
                    'country_code' => 'TW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'TZS',
                    'currency_name' => 'Tanzanian Shilling',
                    'url_image' => 'https://flagsapi.com/TZ/flat/64.png',
                    'country_code' => 'TZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'UAH',
                    'currency_name' => 'Ukrainian Hryvnia',
                    'url_image' => 'https://flagsapi.com/UA/flat/64.png',
                    'country_code' => 'UA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'UGX',
                    'currency_name' => 'Ugandan Shilling',
                    'url_image' => 'https://flagsapi.com/UG/flat/64.png',
                    'country_code' => 'UG',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'USD',
                    'currency_name' => 'United States Dollar',
                    'url_image' => 'https://flagsapi.com/US/flat/64.png',
                    'country_code' => 'US',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'UYU',
                    'currency_name' => 'Uruguayan Peso',
                    'url_image' => 'https://flagsapi.com/UY/flat/64.png',
                    'country_code' => 'UY',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'UZS',
                    'currency_name' => 'Uzbekistan Som',
                    'url_image' => 'https://flagsapi.com/UZ/flat/64.png',
                    'country_code' => 'UZ',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'VND',
                    'currency_name' => 'Vietnamese Dong',
                    'url_image' => 'https://flagsapi.com/VN/flat/64.png',
                    'country_code' => 'VN',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'VUV',
                    'currency_name' => 'Vanuatu Vatu',
                    'url_image' => 'https://flagsapi.com/VU/flat/64.png',
                    'country_code' => 'VU',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'WST',
                    'currency_name' => 'Samoan Tala',
                    'url_image' => 'https://flagsapi.com/WS/flat/64.png',
                    'country_code' => 'WS',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'XAF',
                    'currency_name' => 'CFA Franc BEAC',
                    'url_image' => 'https://flagsapi.com/XAF/flat/64.png',
                    'country_code' => 'XAF',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'XCD',
                    'currency_name' => 'East Caribbean Dollar',
                    'url_image' => 'https://flagsapi.com/XCD/flat/64.png',
                    'country_code' => 'XCD',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'XDR',
                    'currency_name' => 'Special Drawing Rights',
                    'url_image' => 'https://flagsapi.com/SDR/flat/64.png',
                    'country_code' => 'SDR',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'XOF',
                    'currency_name' => 'CFA Franc BCEAO',
                    'url_image' => 'https://flagsapi.com/XOF/flat/64.png',
                    'country_code' => 'XOF',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'XPF',
                    'currency_name' => 'CFP Franc',
                    'url_image' => 'https://flagsapi.com/XPF/flat/64.png',
                    'country_code' => 'XPF',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'YER',
                    'currency_name' => 'Yemeni Rial',
                    'url_image' => 'https://flagsapi.com/YE/flat/64.png',
                    'country_code' => 'YE',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ZAR',
                    'currency_name' => 'South African Rand',
                    'url_image' => 'https://flagsapi.com/ZA/flat/64.png',
                    'country_code' => 'ZA',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ZMW',
                    'currency_name' => 'Zambian Kwacha',
                    'url_image' => 'https://flagsapi.com/ZM/flat/64.png',
                    'country_code' => 'ZM',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_code' => 'ZWL',
                    'currency_name' => 'Zimbabwean Dollar',
                    'url_image' => 'https://flagsapi.com/ZW/flat/64.png',
                    'country_code' => 'ZW',
                    'created_at' => null,
                    'updated_at' => null,
                ],
            ]            
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('physical_currency');
    }
};
